### PR TITLE
375: Depend on xserver-xorg-legacy

### PR DESCRIPTION
**Pull request by jbicha**
Is it ok for me to upload this to artful?
And then to make the SRUs for the other NVIDIA drivers for xenial, yakkety, zesty?

https://launchpad.net/bugs/1559576

I mean you already made this change for [304](https://launchpad.net/ubuntu/+source/nvidia-graphics-drivers-304/304.128-0ubuntu2) and [340](https://launchpad.net/ubuntu/+source/nvidia-graphics-drivers-340/340.93-0ubuntu2) but somehow it wasn't done for the other versions.

### CODE REVIEW

**Comment by tseliot** [comment]
I am going to upload a new release, hopefully this week, and I would like to include one more change, so that it's all SRUed. Your change has been on my TODO list for a while, and I agree that we should get it in ASAP. I'll let you know as soon as that is done.

**Comment by tseliot** [comment]
I changed a few things around, but your changes are now in the 375 branch and it artful. Updates in the stable releases will follow. Thanks for your contribution.

**Comment by jbicha** [comment]
@tseliot Hi, I'm pinging you again because although this was uploaded to artful, it looks like you might have forgotten about the SRUs.

**Comment by tseliot** [comment]
@jbicha I didn't forget. I made the security update (which also includes the dependency) available to our QA team and to our security team about two weeks ago. As soon as the updates land, the dependency will get in.

**Pull request closed without merging**
